package jp.igapyon.mikugrep.cli;

public final class HelpText {
    private HelpText() {
    }

    public static String helpText() {
        return "miku-grep - local-first grep CLI for AI agents and automation\n"
                + "\n"
                + "USAGE\n"
                + "  miku-grep QUERY [ROOT]\n"
                + "  miku-grep QUERY [ROOT] --agent\n"
                + "  miku-grep QUERY [ROOT] --files\n"
                + "  miku-grep QUERY [ROOT] --context N\n"
                + "  miku-grep QUERY [ROOT] --format json\n"
                + "  miku-grep --files [ROOT]\n"
                + "  miku-grep < request.json > result.json\n"
                + "  miku-grep --version\n"
                + "  miku-grep --help\n"
                + "\n"
                + "QUICK EXAMPLES\n"
                + "  miku-grep TODO .\n"
                + "  miku-grep TODO . --context 2\n"
                + "  miku-grep TODO . --files\n"
                + "  miku-grep TODO . --agent\n"
                + "  miku-grep TODO . --format json\n"
                + "  miku-grep TODO . --encoding shift_jis\n"
                + "  miku-grep --files .\n"
                + "\n"
                + "WHEN TO USE\n"
                + "  Use miku-grep when you would normally reach for rg, but want a small\n"
                + "  agent-friendly next step:\n"
                + "    - matching files only:        miku-grep TODO . --files\n"
                + "    - first readable summary:     miku-grep TODO .\n"
                + "    - nearby context:             miku-grep TODO . --context 2\n"
                + "    - next-read candidates:       miku-grep TODO . --agent\n"
                + "    - machine-readable result:    miku-grep TODO . --format json\n"
                + "    - legacy Japanese text:       miku-grep 検索語 . --encoding shift_jis\n"
                + "\n"
                + "CONTRACT\n"
                + "  With QUERY arguments, default output is human-readable text.\n"
                + "  Use --format json for structured result JSON.\n"
                + "  With no arguments, stdin JSON is still accepted and stdout is result JSON.\n"
                + "  stderr is for usage errors, malformed stdin, progress, verbose logs, and unexpected runtime messages.\n"
                + "  Request JSON and result JSON use top-level \"version\": 1.\n"
                + "  Unknown request fields are validation errors.\n"
                + "  Result JSON is pretty-printed like JSON.stringify(result, null, 2), with a trailing newline.\n"
                + "\n"
                + "ARGUMENT OPTIONS\n"
                + "  --agent\n"
                + "    Return a compact next-read summary in text mode.\n"
                + "    In JSON mode, maps to output.mode \"agent\", relevance sort, and readfile hints.\n"
                + "\n"
                + "  --files\n"
                + "    With QUERY, print matching file paths.\n"
                + "    Without QUERY, list files under ROOT like an agent-readable rg --files entry point.\n"
                + "\n"
                + "  --context N\n"
                + "    Show N lines of context around content hits. Maps to output.mode \"detail\".\n"
                + "\n"
                + "  --limit N\n"
                + "    Limit returned matches.\n"
                + "\n"
                + "  --top-files N\n"
                + "    Return agent-oriented top file candidates.\n"
                + "\n"
                + "  --format text|json\n"
                + "    Default for QUERY arguments is text. Use json for machine-readable output.\n"
                + "\n"
                + "  --encoding utf-8|shift_jis\n"
                + "    Decode content with the selected default encoding.\n"
                + "\n"
                + "  --encoding-preset japanese-legacy\n"
                + "    Apply Shift_JIS to common Japanese legacy text file patterns.\n"
                + "\n"
                + "  --ignore-case, -i\n"
                + "    Case-insensitive query.\n"
                + "\n"
                + "  --regex\n"
                + "    Treat QUERY as a regular expression.\n"
                + "\n"
                + "  --glob\n"
                + "    Treat QUERY as a path glob and search file paths.\n"
                + "\n"
                + "  --path\n"
                + "    Search file paths instead of file content.\n"
                + "\n"
                + "  --all-targets\n"
                + "    Search file paths, directory paths, and content.\n"
                + "\n"
                + "  --detect-git-root\n"
                + "    Search upward from ROOT for .git and use that directory as effective root.\n"
                + "\n"
                + "  --no-ignore\n"
                + "    Disable ignore file handling.\n"
                + "\n"
                + "OPTION COMBINATIONS\n"
                + "  --files, --agent/--top-files, and --context are mutually exclusive output modes.\n"
                + "  --regex and --glob are mutually exclusive query modes.\n"
                + "  --path and --all-targets are mutually exclusive target modes.\n"
                + "  --glob implies file path search and cannot be combined with --all-targets.\n"
                + "  Use miku-grep --files . for inventory.\n"
                + "  Use miku-grep TODO --files or miku-grep TODO . --files for matching files.\n"
                + "\n"
                + "EXIT CODES\n"
                + "  0  ok: true, or explicit meta command such as --version / --help\n"
                + "  1  ok: false expected failure with stdout result JSON when possible\n"
                + "  2  malformed stdin or CLI usage error\n"
                + "  3  unexpected runtime error\n"
                + "\n"
                + "MINIMAL REQUEST\n"
                + "  {\n"
                + "    \"version\": 1,\n"
                + "    \"root\": \".\",\n"
                + "    \"query\": { \"type\": \"literal\", \"text\": \"RepositoryMap\" },\n"
                + "    \"search\": { \"targets\": [\"content\"], \"recursive\": true, \"maxDepth\": 8 }\n"
                + "  }\n"
                + "\n"
                + "REQUEST FIELDS\n"
                + "  root\n"
                + "    Search entry directory. Relative paths are resolved from current working directory.\n"
                + "    Result file paths are root-relative and always use \"/\".\n"
                + "\n"
                + "  detectGitRoot\n"
                + "    boolean. Default: false.\n"
                + "    When true, search upward from root for .git and use that directory as effective root.\n"
                + "    effectiveRequest.requestedRoot keeps the input root; effectiveRequest.root is the effective root.\n"
                + "\n"
                + "  query.type\n"
                + "    \"literal\", \"regex\", or \"glob\".\n"
                + "    literal is substring search.\n"
                + "    regex uses Java Pattern, line by line for content search. Regex flags are not accepted directly.\n"
                + "    glob searches root-relative file or directory paths and supports path-level \"**\".\n"
                + "\n"
                + "  query.text\n"
                + "    Non-empty search text or regex pattern.\n"
                + "\n"
                + "  query.case\n"
                + "    \"sensitive\" or \"insensitive\". Default: \"sensitive\".\n"
                + "    In regex search, \"insensitive\" is implemented as case-insensitive matching.\n"
                + "    Ignored for glob search.\n"
                + "\n"
                + "  mode\n"
                + "    \"search\" or \"listFiles\". Default: \"search\".\n"
                + "    \"search\" requires query.\n"
                + "    \"listFiles\" returns file inventory JSON. Optional query must use query.type \"glob\".\n"
                + "\n"
                + "  search.targets\n"
                + "    Non-empty array of \"filepath\", \"directory\", and/or \"content\".\n"
                + "    \"filepath\" searches root-relative file paths.\n"
                + "    \"directory\" searches root-relative directory paths.\n"
                + "    \"content\" searches file contents.\n"
                + "    Default: [\"content\"].\n"
                + "\n"
                + "  search.recursive\n"
                + "    boolean. Default: true.\n"
                + "\n"
                + "  search.maxDepth\n"
                + "    Default: 20 when recursive is true. Maximum: 50.\n"
                + "\n"
                + "  search.maxFileBytes\n"
                + "    Content-read size limit. Default: 10485760. Maximum: 104857600.\n"
                + "\n"
                + "  search.maxLineChars\n"
                + "    Per-line scan limit after decode. Default: 1000000. Maximum: 10000000.\n"
                + "\n"
                + "  search.maxFilesVisited\n"
                + "    Traversal file visit limit. Default: 100000. Maximum: 1000000.\n"
                + "\n"
                + "  search.maxDirectoriesVisited\n"
                + "    Traversal directory visit limit. Default: 10000. Maximum: 100000.\n"
                + "\n"
                + "  search.includeFileNamePatterns\n"
                + "    Optional glob array. Empty or missing means no include restriction.\n"
                + "    MVP glob supports \"*\" and \"?\" within one basename.\n"
                + "\n"
                + "  search.excludeFileNamePatterns\n"
                + "    Optional basename glob excludes.\n"
                + "    When omitted, default excludes are used.\n"
                + "    When specified, this value replaces default excludes.\n"
                + "\n"
                + "  search.excludeDirNamePatterns\n"
                + "    Optional directory basename glob excludes.\n"
                + "    When omitted, default excludes are used.\n"
                + "    When specified, this value replaces default excludes.\n"
                + "\n"
                + "  output.mode\n"
                + "    \"summary\", \"detail\", or \"agent\". Default: \"summary\".\n"
                + "    \"agent\" returns candidate-oriented matches with read range suggestions.\n"
                + "\n"
                + "  output.sort\n"
                + "    \"path\" or \"relevance\". Default: \"path\".\n"
                + "    \"relevance\" sorts summary and agent candidates with deterministic heuristic metadata.\n"
                + "\n"
                + "  output.includeReadfileRequestHints\n"
                + "    boolean. Default: false.\n"
                + "    When true, result.readfileHints contains minimal miku-readfile requests for matched files.\n"
                + "\n"
                + "  output.maxMatches\n"
                + "    Default: 200. Maximum: 10000.\n"
                + "\n"
                + "  output.maxMatchesPerFile\n"
                + "    Default: 20. Maximum: 1000.\n"
                + "\n"
                + "  output.maxLineLength\n"
                + "    Returned snippet limit. Default: 240. Maximum: 4000.\n"
                + "    Snippets contain only source text. Artificial \"...\" is not added.\n"
                + "\n"
                + "  output.maxSnippetsPerFile\n"
                + "    summary representative snippet limit. Default: 3. Maximum: 100.\n"
                + "\n"
                + "  output.contextLines\n"
                + "    detail mode only. Shorthand for contextLinesBefore and contextLinesAfter.\n"
                + "    Default: 0. Maximum: 20.\n"
                + "\n"
                + "  output.contextLinesBefore / output.contextLinesAfter\n"
                + "    detail mode only. Context lines around content hits.\n"
                + "    Default: 0. Maximum: 20.\n"
                + "\n"
                + "  encoding.default\n"
                + "    \"utf-8\" or \"shift_jis\". Default: \"utf-8\".\n"
                + "\n"
                + "  encoding.preset\n"
                + "    Optional. Currently \"japanese-legacy\".\n"
                + "    Accepted in the request contract for upstream parity.\n"
                + "\n"
                + "  encoding.rules\n"
                + "    Array of { \"pathPattern\": \"...\", \"encoding\": \"...\" } or\n"
                + "    { \"fileNamePattern\": \"...\", \"encoding\": \"...\" }.\n"
                + "    pathPattern rules take priority over fileNamePattern rules.\n"
                + "\n"
                + "  encoding.onDecodeError\n"
                + "    \"skip\". Decode failures are reported in diagnostics.\n"
                + "\n"
                + "  ignore.mode\n"
                + "    \"auto\" or \"none\". Default: \"auto\".\n"
                + "    \"auto\" respects .gitignore, .ignore, and .git/info/exclude under root.\n"
                + "    \"none\" disables ignore file handling.\n"
                + "\n"
                + "  ignore.sources\n"
                + "    Optional source selector. Allowed values: \".gitignore\", \".ignore\", \".git/info/exclude\".\n"
                + "    Default: [\".gitignore\", \".ignore\", \".git/info/exclude\"].\n"
                + "\n"
                + "  ignore.useGlobalGitignore\n"
                + "    false. Global gitignore is outside MVP.\n"
                + "\n"
                + "DEFAULT EXCLUDES\n"
                + "  Directory names:\n"
                + "    .git, .svn, node_modules, target, build, dist, .gradle, .idea, .vscode, .settings, vendor\n"
                + "  File name patterns:\n"
                + "    *.class, *.jar, *.zip, *.png, *.jpg, *.jpeg, *.gif, *.pdf, .classpath, .project\n"
                + "\n"
                + "RESULT SHAPE\n"
                + "  {\n"
                + "    \"version\": 1,\n"
                + "    \"ok\": true,\n"
                + "    \"error\": null,\n"
                + "    \"effectiveRequest\": {},\n"
                + "    \"matches\": [],\n"
                + "    \"files\": [],\n"
                + "    \"fileSummary\": {},\n"
                + "    \"readfileHints\": [],\n"
                + "    \"summary\": {\n"
                + "      \"filesVisited\": 0,\n"
                + "      \"directoriesVisited\": 0,\n"
                + "      \"filesScanned\": 0,\n"
                + "      \"directoriesScanned\": 0,\n"
                + "      \"filesMatched\": 0,\n"
                + "      \"directoriesMatched\": 0,\n"
                + "      \"filesIgnored\": 0,\n"
                + "      \"directoriesIgnored\": 0,\n"
                + "      \"matches\": 0,\n"
                + "      \"diagnostics\": 0,\n"
                + "      \"truncated\": false,\n"
                + "      \"truncatedReason\": null\n"
                + "    },\n"
                + "    \"diagnostics\": []\n"
                + "  }\n"
                + "\n"
                + "DETAIL MATCHES\n"
                + "  Content targets return one item per content hit.\n"
                + "  Filepath and directory targets return at most one representative hit per path.\n"
                + "  Content hit:\n"
                + "    { \"type\": \"content\", \"file\": \"src/App.java\", \"line\": 42, \"column\": 7,\n"
                + "      \"matchedText\": \"RepositoryMap\", \"text\": \"class RepositoryMap {\",\n"
                + "      \"trimmed\": false, \"encoding\": \"utf-8\", \"encodingRule\": { \"type\": \"default\" } }\n"
                + "  Content hit with context:\n"
                + "    { \"type\": \"content\", \"file\": \"src/App.java\", \"line\": 42, \"column\": 7,\n"
                + "      \"matchedText\": \"RepositoryMap\", \"text\": \"class RepositoryMap {\",\n"
                + "      \"trimmed\": false,\n"
                + "      \"contextBefore\": [{ \"line\": 41, \"text\": \"\", \"trimmed\": false }],\n"
                + "      \"contextAfter\": [{ \"line\": 43, \"text\": \"}\", \"trimmed\": false }],\n"
                + "      \"encoding\": \"utf-8\", \"encodingRule\": { \"type\": \"default\" } }\n"
                + "  Filepath hit:\n"
                + "    { \"type\": \"filepath\", \"file\": \"src/RepositoryMap.java\",\n"
                + "      \"matchedText\": \"src/RepositoryMap.java\" }\n"
                + "  Directory hit:\n"
                + "    { \"type\": \"directory\", \"path\": \"src\", \"matchedText\": \"src\" }\n"
                + "\n"
                + "SUMMARY MATCHES\n"
                + "  { \"type\": \"file\", \"file\": \"src/RepositoryMap.java\",\n"
                + "    \"matchTypes\": [\"filepath\", \"content\"],\n"
                + "    \"filepathMatched\": true, \"contentMatched\": true,\n"
                + "    \"lines\": [42], \"matchCount\": 1, \"snippets\": [] }\n"
                + "  { \"type\": \"directory\", \"path\": \"src\",\n"
                + "    \"matchTypes\": [\"directory\"], \"directoryMatched\": true, \"matchCount\": 1 }\n"
                + "\n"
                + "AGENT MATCHES\n"
                + "  output.mode \"agent\" returns agentFile / agentDirectory matches with readRanges.\n"
                + "  output.sort \"relevance\" adds relevance score information to summary and agent matches.\n"
                + "\n"
                + "LIST FILES MODE\n"
                + "  mode \"listFiles\" returns top-level files and fileSummary instead of matches.\n"
                + "  When query is supplied, query.type must be \"glob\" and filters root-relative paths.\n"
                + "\n"
                + "READFILE HINTS\n"
                + "  { \"file\": \"src/RepositoryMap.java\",\n"
                + "    \"request\": { \"version\": 1, \"root\": \".\", \"files\": [{ \"path\": \"src/RepositoryMap.java\" }] } }\n"
                + "\n"
                + "FULL STDIN / STDOUT EXAMPLE\n"
                + "  Input:\n"
                + "    { \"version\": 1, \"root\": \".\", \"mode\": \"search\",\n"
                + "      \"query\": { \"type\": \"literal\", \"text\": \"RepositoryMap\", \"case\": \"sensitive\" },\n"
                + "      \"search\": { \"targets\": [\"content\"], \"recursive\": true, \"maxDepth\": 8 },\n"
                + "      \"output\": { \"mode\": \"summary\", \"maxMatches\": 20 } }\n"
                + "\n"
                + "  Possible successful output:\n"
                + "    { \"version\": 1, \"ok\": true, \"error\": null, \"effectiveRequest\": {}, \"matches\": [], \"summary\": {}, \"diagnostics\": [] }\n"
                + "\n"
                + "  Possible validation error output:\n"
                + "    { \"version\": 1, \"ok\": false, \"error\": { \"code\": \"empty_query\", \"message\": \"query.text must not be empty\" }, \"effectiveRequest\": {}, \"matches\": [], \"summary\": {}, \"diagnostics\": [] }\n"
                + "\n"
                + "COMMON DIAGNOSTIC CODES\n"
                + "  Validation / expected failures:\n"
                + "    invalid_request, unknown_field, invalid_version, invalid_mode, invalid_query_type, invalid_query_case,\n"
                + "    invalid_search_targets, invalid_search_target, duplicate_search_target,\n"
                + "    invalid_output_mode, invalid_output_sort, invalid_context_lines, invalid_regex,\n"
                + "    regex_too_large, unsafe_regex,\n"
                + "    invalid_ignore_mode, invalid_ignore_sources, invalid_ignore_source, invalid_ignore_global,\n"
                + "    root_not_found, root_not_accessible, root_too_broad, empty_query,\n"
                + "    max_matches_too_large, max_matches_per_file_too_large, max_depth_too_large,\n"
                + "    max_line_length_too_large, max_snippets_per_file_too_large,\n"
                + "    context_lines_too_large,\n"
                + "    max_file_bytes_too_large, max_line_chars_too_large, max_files_visited_too_large,\n"
                + "    max_directories_visited_too_large, invalid_encoding, invalid_encoding_preset, invalid_encoding_rule\n"
                + "  Runtime diagnostics:\n"
                + "    directory_not_readable, symlink_skipped, file_not_readable,\n"
                + "    max_file_bytes_exceeded, binary_file_skipped, decode_error,\n"
                + "    ignore_file_not_readable, unsupported_ignore_pattern,\n"
                + "    path_escape_skipped, max_matches, max_matches_per_file,\n"
                + "    max_snippets_per_file, max_line_chars_exceeded,\n"
                + "    max_files_visited, max_directories_visited\n"
                + "\n"
                + "ARGUMENT EXAMPLES\n"
                + "  Content search:\n"
                + "    miku-grep TODO .\n"
                + "\n"
                + "  Case-insensitive content search:\n"
                + "    miku-grep repositorymap . --ignore-case\n"
                + "\n"
                + "  Matching files only:\n"
                + "    miku-grep TODO . --files\n"
                + "\n"
                + "  File inventory:\n"
                + "    miku-grep --files .\n"
                + "\n"
                + "  Context lines:\n"
                + "    miku-grep TODO . --context 2\n"
                + "\n"
                + "  Agent next-read summary:\n"
                + "    miku-grep RepositoryMap . --agent\n"
                + "\n"
                + "  JSON output:\n"
                + "    miku-grep TODO . --format json\n"
                + "\n"
                + "  Japanese legacy encoding:\n"
                + "    miku-grep 検索語 . --encoding shift_jis\n"
                + "\n"
                + "JSON EXAMPLES\n"
                + "  Content search:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"query\":{\"type\":\"literal\",\"text\":\"TODO\"},\"search\":{\"targets\":[\"content\"]}}' | miku-grep\n"
                + "\n"
                + "  Case-insensitive content search:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"query\":{\"type\":\"literal\",\"text\":\"repositorymap\",\"case\":\"insensitive\"},\"search\":{\"targets\":[\"content\"]}}' | miku-grep\n"
                + "\n"
                + "  File inventory:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"mode\":\"listFiles\"}' | miku-grep\n"
                + "\n"
                + "  Glob path search:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"query\":{\"type\":\"glob\",\"text\":\"**/*.md\"},\"search\":{\"targets\":[\"filepath\"]}}' | miku-grep\n"
                + "\n"
                + "  Agent summary:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"query\":{\"type\":\"literal\",\"text\":\"RepositoryMap\"},\"output\":{\"mode\":\"agent\"}}' | miku-grep\n"
                + "\n"
                + "  Agent summary with relevance sort:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"query\":{\"type\":\"literal\",\"text\":\"RepositoryMap\"},\"output\":{\"mode\":\"agent\",\"sort\":\"relevance\"}}' | miku-grep\n"
                + "\n"
                + "  Search with readfile hints:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"query\":{\"type\":\"literal\",\"text\":\"RepositoryMap\"},\"output\":{\"includeReadfileRequestHints\":true}}' | miku-grep\n"
                + "\n"
                + "  Japanese legacy encoding preset:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"query\":{\"type\":\"literal\",\"text\":\"検索語\"},\"encoding\":{\"preset\":\"japanese-legacy\"}}' | miku-grep\n"
                + "\n"
                + "  Find-like path search:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"query\":{\"type\":\"regex\",\"text\":\"Repository|docs\"},\"search\":{\"targets\":[\"filepath\",\"directory\"]},\"output\":{\"mode\":\"detail\"}}' | miku-grep\n"
                + "\n"
                + "SEE ALSO\n"
                + "  docs/miku-grep-cli-spec.md\n"
                + "  docs/cli-json-parity.md\n";
    }
}
