package jp.igapyon.mikugrep.cli;

public final class HelpText {
    private HelpText() {
    }

    public static String helpText() {
        return "miku-grep - local-first structured grep CLI for AI agents and automation\n"
                + "\n"
                + "USAGE\n"
                + "  miku-grep < request.json > result.json\n"
                + "  miku-grep --version\n"
                + "  miku-grep --help\n"
                + "\n"
                + "CONTRACT\n"
                + "  Primary input is stdin JSON. Primary output is stdout JSON.\n"
                + "  stdout is reserved for result JSON except --version and --help.\n"
                + "  stderr is for usage errors, malformed stdin, progress, verbose logs, and unexpected runtime messages.\n"
                + "  Request JSON and result JSON use top-level \"version\": 1.\n"
                + "  Unknown request fields are validation errors.\n"
                + "  Result JSON is pretty-printed with 2-space indentation and a trailing newline.\n"
                + "\n"
                + "EXIT CODES\n"
                + "  0  ok: true, or explicit meta command such as --version / --help\n"
                + "  1  ok: false expected failure with stdout result JSON when possible\n"
                + "  2  malformed stdin or CLI usage error\n"
                + "  3  unexpected runtime error\n"
                + "\n"
                + "MINIMAL REQUEST\n"
                + "  {\n"
                + "    \"version\": 1,\n"
                + "    \"root\": \".\",\n"
                + "    \"query\": { \"type\": \"literal\", \"text\": \"RepositoryMap\" },\n"
                + "    \"search\": { \"targets\": [\"content\"], \"recursive\": true, \"maxDepth\": 8 }\n"
                + "  }\n"
                + "\n"
                + "REQUEST FIELDS\n"
                + "  root\n"
                + "    Search entry directory. Relative paths are resolved from current working directory.\n"
                + "    Result file paths are root-relative and always use \"/\".\n"
                + "\n"
                + "  query.type\n"
                + "    \"literal\" or \"regex\".\n"
                + "    literal is case-sensitive substring search.\n"
                + "    regex uses Java Pattern, line by line for content search. Regex flags are not accepted.\n"
                + "\n"
                + "  query.text\n"
                + "    Non-empty search text or regex pattern.\n"
                + "\n"
                + "  search.targets\n"
                + "    Non-empty array of \"filepath\", \"directory\", and/or \"content\".\n"
                + "    \"filepath\" searches root-relative file paths.\n"
                + "    \"directory\" searches root-relative directory paths.\n"
                + "    \"content\" searches file contents.\n"
                + "    Default: [\"content\"].\n"
                + "\n"
                + "  search.recursive\n"
                + "    boolean. Default: true.\n"
                + "\n"
                + "  search.maxDepth\n"
                + "    Default: 20 when recursive is true. Maximum: 50.\n"
                + "\n"
                + "  search.maxFileBytes\n"
                + "    Content-read size limit. Default: 10485760. Maximum: 104857600.\n"
                + "\n"
                + "  search.maxLineChars\n"
                + "    Per-line scan limit after decode. Default: 1000000. Maximum: 10000000.\n"
                + "\n"
                + "  search.maxFilesVisited\n"
                + "    Traversal file visit limit. Default: 100000. Maximum: 1000000.\n"
                + "\n"
                + "  search.maxDirectoriesVisited\n"
                + "    Traversal directory visit limit. Default: 10000. Maximum: 100000.\n"
                + "\n"
                + "  search.includeFileNamePatterns\n"
                + "    Optional glob array. Empty or missing means no include restriction.\n"
                + "    MVP glob supports \"*\" and \"?\" within one basename.\n"
                + "\n"
                + "  search.excludeFileNamePatterns\n"
                + "    Optional basename glob excludes.\n"
                + "    When omitted, default excludes are used.\n"
                + "    When specified, this value replaces default excludes.\n"
                + "\n"
                + "  search.excludeDirNamePatterns\n"
                + "    Optional directory basename glob excludes.\n"
                + "    When omitted, default excludes are used.\n"
                + "    When specified, this value replaces default excludes.\n"
                + "\n"
                + "  output.mode\n"
                + "    \"summary\" or \"detail\". Default: \"summary\".\n"
                + "\n"
                + "  output.maxMatches\n"
                + "    Default: 200. Maximum: 10000.\n"
                + "\n"
                + "  output.maxMatchesPerFile\n"
                + "    Default: 20. Maximum: 1000.\n"
                + "\n"
                + "  output.maxLineLength\n"
                + "    Returned snippet limit. Default: 240. Maximum: 4000.\n"
                + "    Snippets contain only source text. Artificial \"...\" is not added.\n"
                + "\n"
                + "  output.maxSnippetsPerFile\n"
                + "    summary representative snippet limit. Default: 3. Maximum: 100.\n"
                + "\n"
                + "  output.contextLines\n"
                + "    detail mode only. Shorthand for contextLinesBefore and contextLinesAfter.\n"
                + "    Default: 0. Maximum: 20.\n"
                + "\n"
                + "  output.contextLinesBefore / output.contextLinesAfter\n"
                + "    detail mode only. Context lines around content hits.\n"
                + "    Default: 0. Maximum: 20.\n"
                + "\n"
                + "  encoding.default\n"
                + "    \"utf-8\" or \"shift_jis\". Default: \"utf-8\".\n"
                + "\n"
                + "  encoding.rules\n"
                + "    Array of { \"pathPattern\": \"...\", \"encoding\": \"...\" } or\n"
                + "    { \"fileNamePattern\": \"...\", \"encoding\": \"...\" }.\n"
                + "    pathPattern rules take priority over fileNamePattern rules.\n"
                + "\n"
                + "  encoding.onDecodeError\n"
                + "    \"skip\". Decode failures are reported in diagnostics.\n"
                + "\n"
                + "  ignore.mode\n"
                + "    \"auto\" or \"none\". Default: \"auto\".\n"
                + "    \"auto\" respects .gitignore, .ignore, and .git/info/exclude under root.\n"
                + "    \"none\" disables ignore file handling.\n"
                + "\n"
                + "  ignore.sources\n"
                + "    Optional source selector. Allowed values: \".gitignore\", \".ignore\", \".git/info/exclude\".\n"
                + "    Default: [\".gitignore\", \".ignore\", \".git/info/exclude\"].\n"
                + "\n"
                + "  ignore.useGlobalGitignore\n"
                + "    false. Global gitignore is outside MVP.\n"
                + "\n"
                + "DEFAULT EXCLUDES\n"
                + "  Directory names:\n"
                + "    .git, .svn, node_modules, target, build, dist, .gradle, .idea, .vscode, .settings, vendor\n"
                + "  File name patterns:\n"
                + "    *.class, *.jar, *.zip, *.png, *.jpg, *.jpeg, *.gif, *.pdf, .classpath, .project\n"
                + "\n"
                + "RESULT SHAPE\n"
                + "  {\n"
                + "    \"version\": 1,\n"
                + "    \"ok\": true,\n"
                + "    \"error\": null,\n"
                + "    \"effectiveRequest\": {},\n"
                + "    \"matches\": [],\n"
                + "    \"summary\": {\n"
                + "      \"filesVisited\": 0,\n"
                + "      \"directoriesVisited\": 0,\n"
                + "      \"filesScanned\": 0,\n"
                + "      \"directoriesScanned\": 0,\n"
                + "      \"filesMatched\": 0,\n"
                + "      \"directoriesMatched\": 0,\n"
                + "      \"filesIgnored\": 0,\n"
                + "      \"directoriesIgnored\": 0,\n"
                + "      \"matches\": 0,\n"
                + "      \"diagnostics\": 0,\n"
                + "      \"truncated\": false,\n"
                + "      \"truncatedReason\": null\n"
                + "    },\n"
                + "    \"diagnostics\": []\n"
                + "  }\n"
                + "\n"
                + "DETAIL MATCHES\n"
                + "  Content targets return one item per content hit.\n"
                + "  Filepath and directory targets return at most one representative hit per path.\n"
                + "  Content hit:\n"
                + "    { \"type\": \"content\", \"file\": \"src/App.java\", \"line\": 42, \"column\": 7,\n"
                + "      \"matchedText\": \"RepositoryMap\", \"text\": \"class RepositoryMap {\",\n"
                + "      \"trimmed\": false, \"encoding\": \"utf-8\", \"encodingRule\": { \"type\": \"default\" } }\n"
                + "  Content hit with context:\n"
                + "    { \"type\": \"content\", \"file\": \"src/App.java\", \"line\": 42, \"column\": 7,\n"
                + "      \"matchedText\": \"RepositoryMap\", \"text\": \"class RepositoryMap {\",\n"
                + "      \"trimmed\": false,\n"
                + "      \"contextBefore\": [{ \"line\": 41, \"text\": \"\", \"trimmed\": false }],\n"
                + "      \"contextAfter\": [{ \"line\": 43, \"text\": \"}\", \"trimmed\": false }],\n"
                + "      \"encoding\": \"utf-8\", \"encodingRule\": { \"type\": \"default\" } }\n"
                + "  Filepath hit:\n"
                + "    { \"type\": \"filepath\", \"file\": \"src/RepositoryMap.java\",\n"
                + "      \"matchedText\": \"src/RepositoryMap.java\" }\n"
                + "  Directory hit:\n"
                + "    { \"type\": \"directory\", \"path\": \"src\", \"matchedText\": \"src\" }\n"
                + "\n"
                + "SUMMARY MATCHES\n"
                + "  { \"type\": \"file\", \"file\": \"src/RepositoryMap.java\",\n"
                + "    \"matchTypes\": [\"filepath\", \"content\"],\n"
                + "    \"filepathMatched\": true, \"contentMatched\": true,\n"
                + "    \"lines\": [42], \"matchCount\": 1, \"snippets\": [] }\n"
                + "  { \"type\": \"directory\", \"path\": \"src\",\n"
                + "    \"matchTypes\": [\"directory\"], \"directoryMatched\": true, \"matchCount\": 1 }\n"
                + "\n"
                + "FULL STDIN / STDOUT EXAMPLE\n"
                + "  Input:\n"
                + "    { \"version\": 1, \"root\": \".\", \"query\": { \"type\": \"literal\", \"text\": \"RepositoryMap\" },\n"
                + "      \"search\": { \"targets\": [\"content\"], \"recursive\": true, \"maxDepth\": 8 },\n"
                + "      \"output\": { \"mode\": \"summary\", \"maxMatches\": 20 } }\n"
                + "\n"
                + "  Possible successful output:\n"
                + "    { \"version\": 1, \"ok\": true, \"error\": null, \"effectiveRequest\": {}, \"matches\": [], \"summary\": {}, \"diagnostics\": [] }\n"
                + "\n"
                + "  Possible validation error output:\n"
                + "    { \"version\": 1, \"ok\": false, \"error\": { \"code\": \"empty_query\", \"message\": \"query.text must not be empty\" }, \"effectiveRequest\": {}, \"matches\": [], \"summary\": {}, \"diagnostics\": [] }\n"
                + "\n"
                + "COMMON DIAGNOSTIC CODES\n"
                + "  Validation / expected failures:\n"
                + "    invalid_request, unknown_field, invalid_version, invalid_query_type,\n"
                + "    invalid_search_targets, invalid_search_target, duplicate_search_target,\n"
                + "    invalid_output_mode, invalid_context_lines, invalid_regex,\n"
                + "    regex_too_large, unsafe_regex,\n"
                + "    invalid_ignore_mode, invalid_ignore_sources, invalid_ignore_source, invalid_ignore_global,\n"
                + "    root_not_found, root_not_accessible, root_too_broad, empty_query,\n"
                + "    max_matches_too_large, max_matches_per_file_too_large, max_depth_too_large,\n"
                + "    max_line_length_too_large, max_snippets_per_file_too_large,\n"
                + "    context_lines_too_large,\n"
                + "    max_file_bytes_too_large, max_line_chars_too_large, max_files_visited_too_large,\n"
                + "    max_directories_visited_too_large, invalid_encoding, invalid_encoding_rule\n"
                + "  Runtime diagnostics:\n"
                + "    directory_not_readable, symlink_skipped, file_not_readable,\n"
                + "    max_file_bytes_exceeded, binary_file_skipped, decode_error,\n"
                + "    ignore_file_not_readable, unsupported_ignore_pattern,\n"
                + "    path_escape_skipped, max_matches, max_matches_per_file,\n"
                + "    max_snippets_per_file, max_line_chars_exceeded,\n"
                + "    max_files_visited, max_directories_visited\n"
                + "\n"
                + "EXAMPLES\n"
                + "  Content search:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"query\":{\"type\":\"literal\",\"text\":\"TODO\"},\"search\":{\"targets\":[\"content\"]}}' | miku-grep\n"
                + "\n"
                + "  Find-like path search:\n"
                + "    printf '%s\\n' '{\"version\":1,\"root\":\".\",\"query\":{\"type\":\"regex\",\"text\":\"Repository|docs\"},\"search\":{\"targets\":[\"filepath\",\"directory\"]},\"output\":{\"mode\":\"detail\"}}' | miku-grep\n"
                + "\n"
                + "SEE ALSO\n"
                + "  docs/miku-grep-cli-spec.md\n"
                + "  docs/cli-json-parity.md\n";
    }
}
